# Generated by Django 5.1.2 on 2024-10-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_review_anime_remove_review_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.entry'),
        ),
    ]
