# Generated by Django 5.1.2 on 2024-12-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_review_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='description',
            new_name='picture',
        ),
    ]
