# Generated by Django 5.1.2 on 2024-12-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_description_entry_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('book', 'Book'), ('game', 'Game'), ('anime', 'Anime')], default='MOVIE', max_length=100),
        ),
    ]
