# Generated by Django 5.0.6 on 2024-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('tv', 'Tv'), ('book', 'Book'), ('game', 'Game'), ('anime', 'Anime')], default='Tv', max_length=100),
        ),
    ]
